services:
  mongo:
    image: mongo:3.4.4
    environment:
      # MONGO_INITDB_DATABASE: mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - mongodb:/data/db
    restart: always

  # mongo-express:
  #   image: mongo-express
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_AUTH_DATABASE: admin
  #   restart: always

volumes:
  mongodb:
